# 1단계: 의존성 설치
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

# 2단계: 실제 런타임 컨테이너
FROM node:20-alpine
ENV NODE_ENV=production
WORKDIR /app

# Declare build arguments
ARG MONGO_URI
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_S3_BUCKET
ARG JWT_SECRET
ARG REDIS_HOST
ARG REDIS_PORT
ARG OPENAI_API_KEY
ARG ENCRYPTION_KEY
ARG PASSWORD_SALT

# Set environment variables from args
ENV MONGO_URI=${MONGO_URI}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV JWT_SECRET=${JWT_SECRET}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENV PASSWORD_SALT=${PASSWORD_SALT}

COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 5001
CMD ["node", "server.js"]
